
import React, { createContext, useState, useContext, useCallback, useEffect, ReactNode } from 'react';
import { type LanguageCode, SUPPORTED_LANGUAGES, isSupportedLanguage } from '../utils/languages';

type Language = 'ja' | 'en';

/** 完全翻訳済み（UI表示用）。未対応は en にフォールバック */
const FULL_TRANSLATIONS: LanguageCode[] = ['ja', 'en'];

function getDisplayLanguage(code: LanguageCode): 'ja' | 'en' {
  return FULL_TRANSLATIONS.includes(code) ? (code as 'ja' | 'en') : 'en';
}

function getInitialLanguage(): LanguageCode {
  if (typeof navigator === 'undefined') return 'en';
  const raw = navigator.language || (navigator as { userLanguage?: string }).userLanguage || '';
  const base = raw.split('-')[0].toLowerCase();
  if (isSupportedLanguage(base)) return base;
  return 'en';
}

const ja = {
  "header.title": "Dance Music Mastering AI",
  "header.tagline": "30 Years of Mastery | Engineered in Tokyo",
  "footer.copyright": "ALGORITHM MUSIC TOKYO © {year}",
  "section.step1.title": "音源アップロード",
  "section.step2.title": "Beatport/Spotify 配信基準分析",
  "section.step3.title": "AI マスタリング提案・処理",
  "upload.pyodide.loading": "分析システム起動中...",
  "upload.pyodide.installing": "音響解析ライブラリ準備中...",
  "upload.pyodide.ready": "システム準備完了",
  "upload.pyodide.error": "初期化失敗",
  "error.openai.no_key": "OpenAI API キーが設定されていません。",
  "error.openai.fail": "OpenAI からマスタリング提案を取得できませんでした。",
  "error.openai.invalid_params": "OpenAI が有効なマスタリングパラメータを返しませんでした。",
  "error.gemini.no_key": "Gemini API キーが設定されていません。",
  "upload.pyodide.detail": "ブラウザ内で高精度なEBU R 128分析環境を構築しています。",
  "upload.analyzing": "音響スキャン実行中...",
  "upload.analyzing.detail": "LUFS・トゥルービーク・クレストファクター・波形・周波数分布を解析しています。",
  "upload.cta.title": "マスタリングする音源を選択",
  "upload.cta.detail": "WAV / MP3 / AIFF (24bit/44.1kHz以上推奨)",
  "upload.cta.hint": "ドラッグ＆ドロップ または クリックで選択",
  "upload.pyodide.wait": "初回のみ30秒ほどかかることがあります",
  "upload.loaded": "読み込み完了:",
  "upload.aria.label": "音源をアップロード",
  "ux.free_mastering_copy": "無料でAIマスタリングを実行する。（気に入って音源のダウンロードしない限り無料）",
  "ux.upload_first": "まず音源を1曲アップロード",
  "ux.choose_other_file": "別のファイルを選ぶ",
  "ux.select_file_button": "ファイルを選択",
  "ux.error_retry": "別のファイルを選んで再試行",
  "steps.upload": "アップロード",
  "steps.analyze": "分析",
  "steps.run": "実行",
  "steps.listen": "聴く・購入",
  "analysis.waveform.title": "波形解析 (Waveform)",
  "analysis.spectrum.title": "周波数特性 (Spectrum)",
  "analysis.button.get_suggestion": "AIマスタリングを計算する",
  "analysis.button.generating": "エージェントがパラメータを演算中...",
  "analysis.button.copy": "分析レポートをコピー",
  "analysis.metric.lufs": "統合ラウドネス (LUFS)",
  "analysis.metric.peak": "トゥルーピーク (dBTP)",
  "analysis.metric.crest": "クレストファクター (Dynamic)",
  "analysis.metric.width": "ステレオ幅 (Stereo Width)",
  "analysis.metric.rms": "ピークRMS",
  "analysis.metric.bass": "低域エネルギー (Bass)",
  "analysis.target.beatport.lufs": "目標: -8.0 LUFS (-7.0 〜 -9.0)",
  "analysis.target.beatport.peak": "目標: -0.3 dBTP（推奨）",
  "analysis.target.beatport.crest": "目標: 6.0 dB (5.0 〜 8.0)",
  "analysis.target.spotify.lufs": "目標: -14.0 LUFS",
  "analysis.target.spotify.peak": "目標: -1.0 dBTP",
  "analysis.target.spotify.crest": "目標: 9.0 dB (8.0 〜 12.0)",
  "analysis.label.current": "現在値:",
  "analysis.label.target": "配信基準:",
  "analysis.value.db": "{value} dB",
  "analysis.value.dbtp": "{value} dBTP",
  "analysis.value.percent": "{value}%",
  "platform_selector.title": "マスタリング・ターゲット設定",
  "platform.beatport": "Beatport (Techno/Trance)",
  "platform.spotify": "Spotify (Streaming)",
  "agent.idle.title": "AIエージェント待機中",
  "agent.idle.detail": "トラックをアップロードすると、AIが最適な処理パラメータを算出します。",
  "agent.loading.title": "テクノ・トランス基準への最適化中...",
  "agent.loading.detail": "目標値 -8.0 LUFS / -0.3 dBTP への到達経路を計算しています。",
  "agent.params.title": "AI 算出パラメータ (DSP設定)",
  "agent.params.gain": "目標ラウドネスへのゲイン補正",
  "agent.params.limiter": "リミッター・シーリング設定",
  "agent.params.eq": "周波数バランス補正 (EQ)",
  "agent.params.eq.format": ": {gain}dB @ {frequency}Hz (Q: {q})",
  "agent.params.eq.not_needed": "補正不要 (バランス良好)",
  "agent.preview.title": "同一トラック比較プレビュー",
  "agent.preview.mastered": "マスター (AI処理)",
  "agent.preview.original": "オリジナル (A/B比較)",
  "agent.preview.peak_live": "再生中 Peak（判断用）",
  "agent.preview.visualizer": "再生レベル（周波数）",
  "agent.preview.visualizer_idle": "再生でリアルタイム表示",
  "agent.preview.params_short": "Gain / リミッター",
  "agent.file_size": "書き出しサイズ 約 {size}",
  "agent.button.download": "マスタリング済みWAVを書き出し",
  "agent.button.copy_params": "パラメータをコピー (DAW用)",
  "agent.button.processing": "高精度レンダリング中...",
  "common.copied": "コピー完了",
  "console.title": "エージェント行動ログ",
  "language.ja": "日本語",
  "language.en": "English",
  "nav.mastering": "マスタリング",
  "nav.pricing": "料金",
  "nav.login": "ログイン",
  "pricing.title": "料金プラン",
  "pricing.free_preview_cta": "無料プレビュー。30年の感性を移植したAIの音を聴いて、気に入ったら購入してください。",
  "pricing.coming_soon": "準備中です。",
  "nav.library": "ライブラリ",
  "nav.checklist": "チェック",
  "nav.email": "メール",
  "nav.sns": "SNS",
  "nav.mypage": "マイページ",
  "nav.admin": "管理",
  "auth.download_gate.title": "ダウンロードにはログインが必要です",
  "auth.download_gate.description": "Googleでログインするとダウンロードできます。",
  "auth.sign_in_google": "Googleでログイン",
  "auth.cancel": "キャンセル",
  "paywall.title": "ダウンロードには購入が必要です",
  "paywall.description": "WAVのダウンロードは有料プランをご利用ください。料金ページからお支払いいただくと利用可能になります。",
  "paywall.cta": "料金プランを見る",
  "modal.close_back": "閉じてトップへ",
  "modal.close_back_aria": "モーダルを閉じてマスタリング画面に戻る",
  "modal.next_track": "次の曲をアップロード",
  "modal.next_track_aria": "次の曲をアップロードしてマスタリングを続ける",
  "auth.loading": "認証確認中...",
  "auth.sign_out": "ログアウト",
  "mypage.sign_in_required": "マイページ",
  "mypage.sign_in_required_description": "ログインすると、マスタリング履歴の閲覧やダウンロードが可能になります。",
  "mypage.download_history": "マスタリング履歴",
  "mypage.no_history": "まだ履歴がありません",
  "flow.preview_no_login": "30年のエンジニア人生を賭けたフルスキャンAI。ログイン不要でプレビューまで聴けます。",
  "flow.download_gate_after_listen": "すでにプレビューで音は聴けました。気に入ったらログインしてWAVをダウンロード。",
  "flow.preview_then_download": "まず再生で聴いてみて。気に入ったらマスタリングデータを購入（1曲4,000円・ログイン必要）。",
  "flow.complete_teaser": "ログインなしでプレビューまで聴けます。気に入ったら購入してWAVを取得。",
  "result.retry.title": "リトライする",
  "result.retry.problems": "音が割れている。音が曇っている。音がひずんでいる。音に力がない。音が細い。すべてやり直せ。",
  "result.retry.free": "再度マスタリングを実行（無料）",
  "result.purchase_cta": "購入してマイページでダウンロード（4000円）",
  "result.purchase_cta_aria": "マスタリング音源を4,000円で購入。マイページで7日間ダウンロード可能（ログインが必要）",
  "flow.post_login_banner": "ログインしました。マスタリング画面でもう一度プレビューしてダウンロードできます。",
  "flow.post_login_cta": "マスタリングへ",
  "mypage.cta_master_again": "もう1曲マスタリングする",
  "campaign.banner": "今だけ1曲無料キャンペーン中（おひとり様1回限り）",
  "campaign.pricing_lead": "今なら1曲無料キャンペーン実施中。Basic 1曲からご購入いただけます。",
  "paywall.campaign_note": "今なら1曲無料キャンペーン実施中。料金ページで Premium（1曲・¥4,000）をご選択ください。",
  "pricing.checkout_redirecting": "決済ページへ移動中… 切り替わらない場合はポップアップを許可してください",
  "pricing.sign_in_hint": "※ クリックでGoogleログイン画面が開きます",
  "pricing.checkout_failed": "決済の開始に失敗しました。しばらくして再度お試しください。",
  "ux.leave_while_processing": "処理中です。離脱すると結果が失われます。よろしいですか？",
  "campaign.youtube.cta": "応募・お問い合わせ",
  "brand.hardware.spirit": "The Spirit of Japanese Audio.",
  "brand.hardware.lineage": "From the Booth to the Cloud.",
  "brand.hardware.trust": "あなたはCDJを信頼している。Technicsを、Rolandを信頼している。では、マスタリングだけ出所不明のアルゴリズムに任せますか？",
  "brand.hardware.mission": "私たちは、あの機材たちが伝説となった理由である「日本の精密さ・音への執念」をAIマスタリングに持ち込みました。",
  "brand.dynamic.title": "Living Breathing Mastering",
  "brand.dynamic.desc": "他社のAIは、曲を「静止画」として処理します。私たちは「動画」として処理します。ドロップの衝撃を最大化するために、AIがフェーダーを動的に操作します。",
};

const en = {
  "header.title": "Dance Music Mastering AI",
  "header.tagline": "30 Years of Mastery | Engineered in Tokyo",
  "footer.copyright": "ALGORITHM MUSIC TOKYO © {year}",
  "section.step1.title": "Upload Track",
  "section.step2.title": "Distribution Standards Analysis",
  "section.step3.title": "AI Mastering Proposal",
  "upload.pyodide.loading": "Loading Engine...",
  "upload.pyodide.installing": "Installing Libraries...",
  "upload.pyodide.ready": "System Ready",
  "upload.pyodide.error": "Init Error",
  "error.openai.no_key": "OpenAI API key is not set.",
  "error.openai.fail": "Failed to get mastering suggestions from OpenAI.",
  "error.openai.invalid_params": "OpenAI did not return valid mastering parameters.",
  "error.gemini.no_key": "Gemini API key is not set.",
  "upload.pyodide.detail": "Building high-precision analysis environment in browser.",
  "upload.analyzing": "Analyzing Audio...",
  "upload.analyzing.detail": "Measuring LUFS, true peak, crest factor, waveform & frequency spectrum.",
  "upload.cta.title": "Upload Audio",
  "upload.cta.detail": "WAV / MP3 / AIFF (24bit recommended)",
  "upload.cta.hint": "Drag & drop or click to choose",
  "upload.pyodide.wait": "First load may take about 30 seconds",
  "upload.loaded": "Loaded:",
  "upload.aria.label": "Upload file",
  "ux.free_mastering_copy": "Run AI mastering for free. (Free unless you download the mastered file.)",
  "ux.upload_first": "Upload one track to start",
  "ux.choose_other_file": "Choose another file",
  "ux.select_file_button": "Select file",
  "ux.error_retry": "Choose another file to retry",
  "steps.upload": "Upload",
  "steps.analyze": "Analyze",
  "steps.run": "Run",
  "steps.listen": "Listen & Get",
  "analysis.waveform.title": "Waveform Analysis",
  "analysis.spectrum.title": "Frequency Spectrum",
  "analysis.button.get_suggestion": "Generate AI Suggestion",
  "analysis.button.generating": "Agent calculating...",
  "analysis.button.copy": "Copy Analysis Report",
  "analysis.metric.lufs": "Integrated LUFS",
  "analysis.metric.peak": "True Peak",
  "analysis.metric.crest": "Crest Factor",
  "analysis.metric.width": "Stereo Width",
  "analysis.metric.rms": "Peak RMS",
  "analysis.metric.bass": "Bass Energy",
  "analysis.target.beatport.lufs": "Target: -8.0 LUFS (-7.0 to -9.0)",
  "analysis.target.beatport.peak": "Target: -0.3 dBTP (recommended)",
  "analysis.target.beatport.crest": "Target: 6.0 dB (5.0 to 8.0)",
  "analysis.target.spotify.lufs": "Target: -14.0 LUFS",
  "analysis.target.spotify.peak": "Target: -1.0 dBTP",
  "analysis.target.spotify.crest": "Target: 9.0 dB (8.0 to 12.0)",
  "analysis.label.current": "Current:",
  "analysis.label.target": "Standard:",
  "analysis.value.db": "{value} dB",
  "analysis.value.dbtp": "{value} dBTP",
  "analysis.value.percent": "{value}%",
  "platform_selector.title": "Mastering Target Configuration",
  "platform.beatport": "Beatport (Techno/Trance)",
  "platform.spotify": "Spotify (Streaming)",
  "agent.idle.title": "Agent Idle",
  "agent.idle.detail": "Upload a track to get distribution-ready suggestions.",
  "agent.loading.title": "Optimizing for Techno/Trance...",
  "agent.loading.detail": "Calculating path to reach -8.0 LUFS / -0.3 dBTP.",
  "agent.params.title": "AI Proposed Parameters",
  "agent.params.gain": "Gain Adjustment for LUFS",
  "agent.params.limiter": "Peak Limiting Configuration",
  "agent.params.eq": "Frequency Balance Correction",
  "agent.params.eq.format": ": {gain}dB @ {frequency}Hz (Q: {q})",
  "agent.params.eq.not_needed": "No correction needed",
  "agent.preview.title": "A/B Preview",
  "agent.preview.mastered": "Master (AI)",
  "agent.preview.original": "Original (A/B)",
  "agent.preview.peak_live": "Peak (live, for A/B)",
  "agent.preview.visualizer": "Playback level (frequency)",
  "agent.preview.visualizer_idle": "Real-time when playing",
  "agent.preview.params_short": "Gain / Limiter",
  "agent.file_size": "Export size ~{size}",
  "agent.button.download": "Export Mastered WAV",
  "agent.button.copy_params": "Copy Parameters (for DAW)",
  "agent.button.processing": "Exporting Audio...",
  "common.copied": "Copied!",
  "console.title": "AI Analysis Logs",
  "language.ja": "日本語",
  "language.en": "English",
  "nav.mastering": "Mastering",
  "nav.pricing": "Pricing",
  "nav.login": "Login",
  "pricing.title": "Pricing Plans",
  "pricing.free_preview_cta": "Free preview. Hear the AI that digitizes 30 years of mastery. If you like it, purchase.",
  "pricing.coming_soon": "Coming soon.",
  "nav.library": "Library",
  "nav.checklist": "Check",
  "nav.email": "Email",
  "nav.sns": "SNS",
  "nav.mypage": "My Page",
  "nav.admin": "Admin",
  "auth.download_gate.title": "Sign in to download",
  "auth.download_gate.description": "Sign in with Google to download your mastered file.",
  "auth.sign_in_google": "Sign in with Google",
  "auth.cancel": "Cancel",
  "paywall.title": "Purchase required to download",
  "paywall.description": "WAV download requires a paid plan. Visit the pricing page to purchase.",
  "paywall.cta": "View pricing",
  "modal.close_back": "Close (back to top)",
  "modal.close_back_aria": "Close modal and return to mastering screen",
  "modal.next_track": "Upload Next Track",
  "modal.next_track_aria": "Upload next track and continue mastering",
  "auth.loading": "Verifying authentication...",
  "auth.sign_out": "Sign out",
  "mypage.sign_in_required": "My Page",
  "mypage.sign_in_required_description": "Sign in to view your mastering history and access downloads.",
  "mypage.download_history": "Mastering History",
  "mypage.no_history": "No history yet",
  "flow.preview_no_login": "Mastered by 30 years of experience. No sign-in needed to listen to the full preview.",
  "flow.download_gate_after_listen": "You've already heard the preview. Like it? Sign in to download the WAV.",
  "flow.preview_then_download": "Play and listen first. Like it? Purchase mastering data (¥4,000/track, sign-in required).",
  "flow.complete_teaser": "Preview with no sign-in. Like it? Purchase to get the WAV.",
  "result.retry.title": "Retry",
  "result.retry.problems": "Clipping, muddy, distorted, no punch, thin? Run it again.",
  "result.retry.free": "Re-run mastering (free)",
  "result.purchase_cta": "Purchase → Download from My Page (¥4,000)",
  "result.purchase_cta_aria": "Purchase mastered file for ¥4,000. Download from My Page within 7 days (sign-in required)",
  "flow.post_login_banner": "You're signed in. Go to Mastering to preview again and download.",
  "flow.post_login_cta": "Go to Mastering",
  "mypage.cta_master_again": "Master another track",
  "campaign.banner": "Limited time: 1 track free (one per person)",
  "campaign.pricing_lead": "1 track free campaign now. Start with Basic (1 track).",
  "paywall.campaign_note": "1 track free campaign. Select Premium (1 track, ¥4,000) on the pricing page.",
  "pricing.checkout_redirecting": "Redirecting to checkout… Allow pop-ups if the page doesn't change",
  "pricing.sign_in_hint": "Click to open Google sign-in",
  "pricing.checkout_failed": "Could not start checkout. Please try again later.",
  "ux.leave_while_processing": "Processing in progress. Leave anyway? Progress will be lost.",
  "campaign.youtube.cta": "Apply / Contact",
  "brand.hardware.spirit": "The Spirit of Japanese Audio.",
  "brand.hardware.lineage": "From the Booth to the Cloud.",
  "brand.hardware.trust": "You trust your CDJs. You trust your Technics. You trust your Roland synths. Why trust your mastering to a random algorithm?",
  "brand.hardware.mission": "We bring the same Japanese precision, durability, and obsession with sound quality to AI mastering.",
  "brand.dynamic.title": "Living Breathing Mastering",
  "brand.dynamic.desc": "Other AIs treat your track as a static image. We treat it as a moving experience. The AI dynamically rides the faders to maximize the impact of your drop.",
};

const translations: Record<Language, Record<string, string>> = { ja, en };

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, options?: { replacements?: Record<string, string | number>, default?: string }) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => getDisplayLanguage(getInitialLanguage()));
  const t = useCallback((key: string, options?: { replacements?: Record<string, string | number>, default?: string }) => {
    let translation = translations[language][key] || options?.default || key;
    if (options?.replacements) {
      Object.entries(options.replacements).forEach(([key, value]) => {
        translation = translation.replace(`{${key}}`, String(value));
      });
    }
    return translation;
  }, [language]);
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useTranslation must be used within a LanguageProvider');
  return context;
};
